CREATE SEQUENCE IF NOT EXISTS authors_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS book_borrowings_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS books_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS categories_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS publishers_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE authors
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    birth_date date,
    country    VARCHAR(255),
    name       VARCHAR(255)                            NOT NULL,
    CONSTRAINT authors_pkey PRIMARY KEY (id)
);

CREATE TABLE book_borrowings
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    borrower_email VARCHAR(255)                            NOT NULL,
    borrower_name  VARCHAR(255)                            NOT NULL,
    borrowing_date date                                    NOT NULL,
    return_date    date,
    book_id        BIGINT,
    CONSTRAINT book_borrowings_pkey PRIMARY KEY (id)
);

CREATE TABLE book_categories
(
    book_id     BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    CONSTRAINT book_categories_pkey PRIMARY KEY (book_id, category_id)
);

CREATE TABLE books
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255)                            NOT NULL,
    publication_year INTEGER,
    stock            INTEGER                                 NOT NULL,
    author_id        BIGINT,
    publisher_id     BIGINT,
    CONSTRAINT books_pkey PRIMARY KEY (id)
);

CREATE TABLE categories
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(255),
    name        VARCHAR(255)                            NOT NULL,
    CONSTRAINT categories_pkey PRIMARY KEY (id)
);

CREATE TABLE publishers
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    address            TEXT,
    establishment_year INTEGER,
    name               VARCHAR(255)                            NOT NULL,
    CONSTRAINT publishers_pkey PRIMARY KEY (id)
);

ALTER TABLE categories
    ADD CONSTRAINT ukt8o6pivur7nn124jehx7cygw5 UNIQUE (name);

ALTER TABLE book_categories
    ADD CONSTRAINT fk3k3ahp5vqlgmrr9swqqprmbxy FOREIGN KEY (book_id) REFERENCES books (id) ON DELETE NO ACTION;

ALTER TABLE books
    ADD CONSTRAINT fkayy5edfrqnegqj3882nce6qo8 FOREIGN KEY (publisher_id) REFERENCES publishers (id) ON DELETE NO ACTION;

ALTER TABLE books
    ADD CONSTRAINT fkfjixh2vym2cvfj3ufxj91jem7 FOREIGN KEY (author_id) REFERENCES authors (id) ON DELETE NO ACTION;

ALTER TABLE book_borrowings
    ADD CONSTRAINT fkpo78cf0ph5ya90glc7wv57wdj FOREIGN KEY (book_id) REFERENCES books (id) ON DELETE NO ACTION;

ALTER TABLE book_categories
    ADD CONSTRAINT fkrg2xlmc92mm2y5b1wmhd2g0y0 FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE NO ACTION;

-- SEED DATA
-- PUBLISHERS
INSERT INTO publishers (id, name, establishment_year, address) VALUES
                                                                   (1, 'Atlas Publishing', 1986, 'Istanbul, Turkey'),
                                                                   (2, 'Northwind Books', 1998, 'Ankara, Turkey'),
                                                                   (3, 'Blue Harbor Press', 2005, 'Izmir, Turkey'),
                                                                   (4, 'Cedar House', 2012, 'Bursa, Turkey'),
                                                                   (5, 'Orion Print', 1975, 'Antalya, Turkey');

-- AUTHORS
INSERT INTO authors (id, name, birth_date, country) VALUES
                                                        (1, 'Orhan Demir',  '1978-03-12', 'Turkey'),
                                                        (2, 'Elif Kaya',   '1984-11-05', 'Turkey'),
                                                        (3, 'Mert Yalcin', '1969-06-21', 'Turkey'),
                                                        (4, 'Zeynep Arslan','1990-01-17', 'Turkey'),
                                                        (5, 'Deniz Sahin', '1972-09-02', 'Turkey');

-- CATEGORIES
INSERT INTO categories (id, name, description) VALUES
                                                   (1, 'Fiction',     'Novels and fiction works'),
                                                   (2, 'Sci-Fi',      'Science fiction'),
                                                   (3, 'History',     'History and research'),
                                                   (4, 'Technology',  'Software and technology'),
                                                   (5, 'Philosophy',  'Philosophy and thought');

-- BOOKS
INSERT INTO books (id, name, publication_year, stock, author_id, publisher_id) VALUES
                                                                                   (1, 'Lost City',            2012, 12, 1, 1),
                                                                                   (2, 'Behind the Shadows',   2016,  7, 2, 2),
                                                                                   (3, 'AI 101',               2021, 20, 3, 2),
                                                                                   (4, 'At the Edge of Time',  2019,  5, 4, 3),
                                                                                   (5, 'Modern History Notes', 2018,  6, 5, 5);

-- BOOK_CATEGORIES
INSERT INTO book_categories (book_id, category_id) VALUES
                                                       (1, 1),  -- Lost City -> Fiction
                                                       (2, 5),  -- Behind the Shadows -> Philosophy
                                                       (3, 4),  -- AI 101 -> Technology
                                                       (4, 2),  -- At the Edge of Time -> Sci-Fi
                                                       (5, 3);  -- Modern History Notes -> History

-- BOOK_BORROWINGS
INSERT INTO book_borrowings (id, borrower_name, borrower_email, borrowing_date, return_date, book_id) VALUES
                                                                                                          (1, 'Ali Yilmaz',   'ali@example.com',   '2026-01-20', '2026-01-28', 1),
                                                                                                          (2, 'Ayse Demir',   'ayse@example.com',  '2026-02-01', '2026-02-09', 2),
                                                                                                          (3, 'Mehmet Can',   'mehmet@example.com','2026-01-15', '2026-01-25', 3),
                                                                                                          (4, 'Selin Ak',     'selin@example.com', '2026-02-10', '2026-02-14', 4),
                                                                                                          (5, 'Burak Koc',    'burak@example.com', '2026-01-30', '2026-02-05', 5);
